language: python
python:
  - "3.9"

branches:
  only:
    - feature/upgrade-junction

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install nox

script:
  - nox -s test
  - nox -s lint