name: Junction

on:
  push:
    branches:
      - feature/*

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install verison tools
      run: |
        pip install versiontools
        pip install -r requirements.txt
    # - name: Run test cases
    #   run: |
    #     pip install -r tools/requirements-test.txt
    #     python manage.py test
    # - name: Coverage check
    #   run: |
    #     pip install coverage
    #     coverage run manage.py test
    #     coverage report
    - name: Django Coverage action
      uses: actions/python-django-coverage-gitHub-action@0.9
      with:
        django-app: 'tests/integrations'
        minimum-coverage: '80'
    # - name: Lint with flake8
    #   continue-on-error: true
    #   run: |
    #     pip install flake8
    #     flake8
    # - name: Build and pUsh docker image
    #   run: |
    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "Sandee246" --password-stdin
    #     docker image build -t
    #     docker push
    # - name: Log in to Docker Hub
    #     uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Extract metadata (tags, labels) for Docker
    #     id: meta
    #     uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #     with:
    #       images: my-docker-hub-namespace/my-docker-hub-repository
      
    #   - name: Build and push Docker image
    #     uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #     with:
    #       context: .
    #       push: true
    #       tags: ${{ steps.meta.outputs.tags }}
    #       labels: ${{ steps.meta.outputs.labels }}